cisco:
  hosts:
    R1:
      ansible_host: 192.168.122.11
      ansible_user: devnet
      ansible_password: devnet123
      config_file: router1.txt
    R2:
      ansible_host: 192.168.122.12
      ansible_user: devnet
      ansible_password: devnet123
      config_file: router2.txt
  vars:
    ansible_connection: network_cli
    ansible_network_os: "ios"
    ansible_become: yes
    #ansible_become_method: enable
    ansible_become_password: trabajo1
    ping: pong
